name: release

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Publish to pkg.go.dev
        run: GOPROXY=proxy.golang.org go list -m github.com/phiryll/kv@${{ github.ref_name }}
